import { IPAThemeVarCollection, CSSVariableTheme } from "./types";
export default function getAntdThemeVars(
  themeVars: IPAThemeVarCollection
): CSSVariableTheme {
  return {
    "--ant-primary-color": themeVars["--primary-color"],
    "--ant-primary-color-hover": themeVars["--primary-color-hover"],
    "--ant-primary-color-outline": themeVars["--input-focus-box-shadow"], //input：focus的box-shadow，从rgba(24, 144, 255, 0.2)改为现在这个颜色
    "--ant-primary-1": themeVars["--hovered-item-background"],
    "--ant-primary-2": "#bae7ff",
    "--ant-primary-3": "#91d5ff",
    "--ant-primary-4": "#69c0ff",
    "--ant-primary-5": themeVars["--primary-color-hover"], //antd的input输入框悬浮的border颜色更改，从'#40a9ff'更改为现在这个颜色
    "--ant-primary-6": "#1890ff",
    "--ant-primary-7": themeVars["--primary-color-active"],
    "--ant-primary-color-deprecated-l-35": "#cbe6ff",
    "--ant-primary-color-deprecated-l-20": "#7ec1ff",
    "--ant-primary-color-deprecated-t-20": "#46a6ff",
    "--ant-primary-color-deprecated-t-50": "#8cc8ff",
    "--ant-primary-color-deprecated-f-12": "rgba(24, 144, 255, 0.12)",
    "--ant-primary-color-active-deprecated-f-30": "rgba(230, 247, 255, 0.3)",
    "--ant-primary-color-active-deprecated-d-02": "#dcf4ff",
    "--ant-success-color": "#52c41a",
    "--ant-success-color-hover": "#73d13d",
    "--ant-success-color-active": "#389e0d",
    "--ant-success-color-outline": "rgba(82, 196, 26, 0.2)",
    "--ant-success-color-deprecated-bg": "#f6ffed",
    "--ant-success-color-deprecated-border": "#b7eb8f",
    "--ant-error-color": "#ff4d4f",
    "--ant-error-color-hover": "#ff7875",
    "--ant-error-color-active": "#d9363e",
    "--ant-error-color-outline": "rgba(255, 77, 79, 0.2)",
    "--ant-error-color-deprecated-bg": "#fff2f0",
    "--ant-error-color-deprecated-border": "#ffccc7",
    "--ant-warning-color": "#faad14",
    "--ant-warning-color-hover": "#ffc53d",
    "--ant-warning-color-active": "#d48806",
    "--ant-warning-color-outline": "rgba(250, 173, 20, 0.2)",
    "--ant-warning-color-deprecated-bg": "#fffbe6",
    "--ant-warning-color-deprecated-border": "#ffe58f",
    "--ant-info-color": "#1890ff",
    "--ant-info-color-deprecated-bg": "#e6f7ff",
    "--ant-info-color-deprecated-border": "#91d5ff",
    // //Extra variables we add
    // "--ant-extra-primary-text-color": themeVars["--primary-text-color"],
    // "--ant-extra-disabled-text-color": themeVars["--disabled-text-color"],
    // "--ant-extra-label-text-color": themeVars["--label-text-color"],
    // "--ant-extra-app-background": themeVars["--app-background"],
    // "--ant-extra-item-background": themeVars["--card-background"],
    // "--ant-extra-item-hover-background": themeVars["--hovered-item-background"],
    // "--ant-extra-border-color": themeVars["--border-color"],
    // "--ant-extra-primary-contrast": themeVars["--primary-contrast"],
    // "--ant-extra-dropdown-shadow": themeVars["--dropdown-shadow"],
    // "--ant-primary-color-active": themeVars["--primary-color-active"],
    // "--ant-extra-dialog-background": themeVars["--dialog-background-color"],
    // "--ant-tooltip-bgColor": themeVars["--tooltip-background-color"],
    // "--ant-modal-bgColor": themeVars["--modal-background-color"],
    // "--ant-mask-bgColor": themeVars["--mark-background-color"],
    // "--ant-collapse-bgColor": themeVars["--collapse-bgColor"],
  };
}
